# Section "InputClass"
#        Identifier "tap-by-default"
#        MatchIsTouchpad "on"
#        MatchDriver "libinput"
#        Option "Tapping" "on"
#        Option "Enabled" "off"
# EndSection
Section "InputClass"
    Identifier "disable-touchpad"
    MatchIsTouchpad "on"
    Option "Ignore" "on"
EndSection
