#!/usr/bin/env bash

## Adapted for dmenu

# Import Colors
. "$HOME/.cache/wal/colors.sh"

# Theme Elements
pc_cmd='playerctl -p spotify'
spotify_status="`$pc_cmd status 2>/dev/null`"

if [[ "$spotify_status" = 'Playing' ]]; then
	if [[ "`$pc_cmd metadata title`" == 'Advertisement' ]]; then
		prompt='AD'
	else
		prompt="`$pc_cmd metadata artist`"
	fi
elif [[ "$spotify_status" = 'Paused' ]]; then
		prompt="`$pc_cmd metadata artist`"
else
	prompt='Offline'
fi

# Options
if [[ ${spotify_status} == 'Playing' ]]; then
	option_1=' Pause'
else
	option_1=' Play'
fi
option_2=' Stop'
option_3=' Previous'
option_4=' Next'
option_5=' Repeat'
option_6=' Random'

# Visual feedback for toggle states
if [[ "`$pc_cmd loop`" != 'None' ]]; then
    option_5=" Repeat [ON]"
else
    option_5=" Repeat [OFF]"
fi

if [[ "`$pc_cmd shuffle`" == 'On' ]]; then
    option_6=" Random [ON]"
else
    option_6=" Random [OFF]"
fi

# Theme settings
FONT='Iosevka Nerd Font-14'
NB="$color0"
NF="$color15"
SB="$color1"
SF="$color15"

# Dmenu CMD
dmenu_cmd() {
	dmenu \
		-p "$prompt" \
		-fn "$FONT" \
		-nb "$NB" \
		-nf "$NF" \
		-sb "$SB" \
		-sf "$SF"
}

# Pass variables to dmenu
run_dmenu() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | dmenu_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		${pc_cmd} play-pause
	elif [[ "$1" == '--opt2' ]]; then
		${pc_cmd} stop
	elif [[ "$1" == '--opt3' ]]; then
		${pc_cmd} previous
	elif [[ "$1" == '--opt4' ]]; then
		${pc_cmd} next
	elif [[ "$1" == '--opt5' ]]; then
		if [[ "`$pc_cmd loop`" == 'None' ]]; then
			${pc_cmd} loop playlist
		else
			${pc_cmd} loop none
		fi
	elif [[ "$1" == '--opt6' ]]; then
		${pc_cmd} shuffle toggle
	fi
}

# Actions
chosen="$(run_dmenu)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    *"Repeat"*) 
		run_cmd --opt5
        ;;
    *"Random"*) 
		run_cmd --opt6
        ;;
esac
