#!/usr/bin/env bash

## Adapted for dmenu

# Import Colors
. "$HOME/.cache/wal/colors.sh"

# Theme Elements
prompt="$(hostname) ($(echo $DESKTOP_SESSION))"

# Options
option_1=" Lock"
option_2=" Logout"
option_3=" Suspend"
option_4=" Hibernate"
option_5=" Reboot"
option_6=" Shutdown"

yes=' Yes'
no=' No'

# Theme settings
FONT='Iosevka Nerd Font-14'
NB="$color0"
NF="$color15"
SB="$color2"
SF="$color15"

# Dmenu CMD
dmenu_cmd() {
  dmenu \
    -p "$prompt" \
    -fn "$FONT" \
    -nb "$NB" \
    -nf "$NF" \
    -sb "$SB" \
    -sf "$SF"
}

# Pass variables to dmenu
run_dmenu() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | dmenu_cmd
}

# Confirmation CMD
confirm_cmd() {
  dmenu \
    -p 'Confirmation' \
    -fn "$FONT" \
    -nb "$NB" \
    -nf "$NF" \
    -sb "$SB" \
    -sf "$SF"
}

# Ask for confirmation
confirm_exit() {
  echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {
  selected="$(confirm_exit)"
  if [[ "$selected" == "$yes" ]]; then
    ${1} && ${2} && ${3}
  else
    exit
  fi
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    betterlockscreen --lock
  elif [[ "$1" == '--opt2' ]]; then
    confirm_run 'kill -9 -1'
  elif [[ "$1" == '--opt3' ]]; then
    confirm_run 'mpc -q pause' 'pulsemixer --mute' 'betterlockscreen --suspend'
  elif [[ "$1" == '--opt4' ]]; then
    confirm_run 'systemctl hibernate'
  elif [[ "$1" == '--opt5' ]]; then
    confirm_run 'systemctl reboot'
  elif [[ "$1" == '--opt6' ]]; then
    confirm_run 'systemctl poweroff'
  fi
}

# Actions
chosen="$(run_dmenu)"
case ${chosen} in
$option_1)
  run_cmd --opt1
  ;;
$option_2)
  run_cmd --opt2
  ;;
$option_3)
  run_cmd --opt3
  ;;
$option_4)
  run_cmd --opt4
  ;;
$option_5)
  run_cmd --opt5
  ;;
$option_6)
  run_cmd --opt6
  ;;
esac
