#!/usr/bin/env bash

## Adapted for dmenu

# Import Colors
. "$HOME/.cache/wal/colors.sh"

# Import Current Theme
DIR="$HOME/.config/xmonad"
ASROOT="$DIR/scripts/xmonad_asroot"

# Theme Elements
prompt='Root'
term='kitty --config /home/user/.config/kitty/kitty.conf'

# Options
option_1=" Kitty"
option_2=" Thunar"
option_3=" Geany"
option_4=" Yazi"
option_5=" Neovim"

# Theme settings
FONT='Iosevka Nerd Font-14'
NB="$color0"
NF="$color15"
SB="$color2"
SF="$color15"

# Dmenu CMD
dmenu_cmd() {
  dmenu \
    -p "$prompt" \
    -fn "$FONT" \
    -nb "$NB" \
    -nf "$NF" \
    -sb "$SB" \
    -sf "$SF"
}

# Pass variables to dmenu
run_dmenu() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | dmenu_cmd
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    ${ASROOT} "$term"
  elif [[ "$1" == '--opt2' ]]; then
    ${ASROOT} 'dbus-run-session thunar'
  elif [[ "$1" == '--opt3' ]]; then
    ${ASROOT} geany
  elif [[ "$1" == '--opt4' ]]; then
    ${ASROOT} "$term -e yazi"
  elif [[ "$1" == '--opt5' ]]; then
    ${ASROOT} "$term -e nvim"
  fi
}

# Actions
chosen="$(run_dmenu)"
case ${chosen} in
$option_1)
  run_cmd --opt1
  ;;
$option_2)
  run_cmd --opt2
  ;;
$option_3)
  run_cmd --opt3
  ;;
$option_4)
  run_cmd --opt4
  ;;
$option_5)
  run_cmd --opt5
  ;;
esac
